package net.yggawg.mobile.warp

import kotlinx.serialization.Serializable
import kotlinx.serialization.encodeToString
import kotlinx.serialization.json.Json

/**
 * WARP-аккаунт, зарегистрированный через Cloudflare API.
 *
 * Приватный ключ X25519 генерируется на устройстве и НИКОГДА не покидает телефон.
 * В Cloudflare уходит только публичная часть.
 */
data class WarpConfig(
    /** X25519 private key (base64, 32 bytes) */
    val privateKey: String,
    /** Peer public key от Cloudflare (base64) */
    val peerPublicKey: String,
    /** Client IPv4 адрес (например 172.16.0.2) */
    val clientV4: String,
    /** Client IPv6 адрес */
    val clientV6: String,
    /** Client ID (base64, 3 bytes) — reserved для WireGuard */
    val clientId: String,
    /** Account ID от Cloudflare */
    val accountId: String = "",
    /** Device ID от Cloudflare */
    val deviceId: String = "",
    /** Bearer token (для PATCH license) */
    val token: String = "",
    /** Endpoint: host:port */
    val endpoint: String = DEFAULT_ENDPOINT,
    /** WARP+ license key (если введён пользователем) */
    val license: String? = null,
    /** WARP+ активирован */
    val warpPlus: Boolean = false,
    /** ISO8601 момент регистрации */
    val createdAt: String = "",
) {
    companion object {
        const val DEFAULT_ENDPOINT = "engage.cloudflareclient.com:2408"
        const val DEFAULT_MTU = 1280

        /**
         * Собрать wireguard:// URI для импорта.
         */
        fun toWireGuardUri(config: WarpConfig): String {
            val reserved = parseReserved(config.clientId)
            val addrs = listOfNotNull(config.clientV4, config.clientV6.takeIf { it.isNotEmpty() }).joinToString(",")
            val tag = if (config.warpPlus) "WARP+" else "WARP"

            val params = mutableListOf<String>()
            params.add("publickey=${config.peerPublicKey}")
            params.add("address=$addrs")
            params.add("allowedips=0.0.0.0/0,::/0")
            params.add("mtu=${DEFAULT_MTU}")
            if (reserved != null) params.add("reserved=${reserved.joinToString(",")}")

            val query = params.joinToString("&")
            return "wireguard://${config.privateKey}@${config.endpoint}?$query#$tag"
        }

        /**
         * Собрать WireGuard .conf текст для импорта в приложение.
         */
        fun toWireGuardConf(config: WarpConfig, includeReserved: Boolean = true): String {
            val sb = StringBuilder()
            val tag = if (config.warpPlus) "WARP+" else "WARP"
            val addrs = listOfNotNull(config.clientV4, config.clientV6.takeIf { it.isNotEmpty() }).joinToString(", ")

            sb.appendLine("# $tag (generated by Holowbark)")
            sb.appendLine("[Interface]")
            sb.appendLine("PrivateKey = ${config.privateKey}")
            sb.appendLine("Address = $addrs")
            sb.appendLine("MTU = $DEFAULT_MTU")
            sb.appendLine()
            sb.appendLine("[Peer]")
            sb.appendLine("PublicKey = ${config.peerPublicKey}")
            sb.appendLine("AllowedIPs = 0.0.0.0/0, ::/0")
            sb.appendLine("Endpoint = ${config.endpoint}")

            if (includeReserved) {
                val reserved = parseReserved(config.clientId)
                if (reserved != null) {
                    sb.appendLine("Reserved = ${reserved.joinToString(",")}")
                }
            }

            return sb.toString()
        }

        /**
         * Парсит client_id (base64, 3 байта) в список десятичных чисел для Reserved.
         */
        fun parseReserved(clientId: String): List<Int>? {
            return try {
                val bytes = android.util.Base64.decode(clientId, android.util.Base64.DEFAULT)
                if (bytes.size != 3) return null
                bytes.map { it.toInt() and 0xFF }
            } catch (_: Exception) {
                null
            }
        }
    }
}

/**
 * Модель для warp_endpoints.json.
 */
@Serializable
data class WarpEndpoints(
    val wireguard: WireGuardEndpoints = WireGuardEndpoints(),
    val masque: MasqueEndpoints = MasqueEndpoints(),
)

@Serializable
data class WireGuardEndpoints(
    val v4_cidr: List<String> = emptyList(),
    val v6_cidr: List<String> = emptyList(),
    val ports: List<Int> = emptyList(),
    val ports_extra: List<Int> = emptyList(),
    val sni_pool: List<String> = emptyList(),
)

@Serializable
data class MasqueEndpoints(
    val v4_cidr: List<String> = emptyList(),
    val h3_v4_cidr: List<String> = emptyList(),
    val ports_h3: List<Int> = emptyList(),
    val ports_h2: List<Int> = emptyList(),
    val sni_pool: List<String> = emptyList(),
)

/** Парсинг warp_endpoints.json */
fun parseWarpEndpoints(json: String): WarpEndpoints {
    return Json { ignoreUnknownKeys = true }.decodeFromString(json)
}
